# -------------- 公司签到 ----------------
spring:
  jmx:
    enabled: false
  application:
    name: web
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  #数据源
  datasource:
    url: jdbc:mysql://172.168.95.9:3306/lzslj_company_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&&serverTimezone=CST
    username: root
    password: rjgs@2016
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化时建立物理连接的个数
    initial-size: 5
    # 最大连接池数量
    max-active: 20
    # 最小连接池数量
    min-idle: 5
    # 获取连接时最大等待时间
    max-wait: 60000
    # 是否缓存preparedStatement，也就是PSCache。
    pool-prepared-statements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: -1
    # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
    validation-query: SELECT 1 FROM DUAL
    # 单位：秒，检测连接是否有效的超时时间。
    validation-query-timeout: 1
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-borrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    time-between-eviction-runs-millis: 6000
    # 连接保持空闲而不被驱逐的最小时间
    min-evictable-idle-time-millis: 1800000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    # 配置监控服务器
    stat-view-servlet:
      login-username: admin
      login-password: rjgs@2016
      reset-enable: false
      url-pattern: /druid/*

  tomcat:
    test-while-idle: true

  #freemarker配置
  freemarker:
    settings:
      template_update_delay: 0
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      boolean_format: true,false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.######
      whitespace_stripping: true
      classic_compatible: true
  jpa:
    #打印sql
    show-sql: true
    hibernate:
      naming:
        #表的命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #自动建表
      ddl-auto: update

mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true
  mybatis:
    configuration:
      map-underscore-to-camel-case: false


logging:
  level:
    com.jsdc.rfid.mapper: debug

jsdc:
  tokenExpireTime: 5
  filepath: C:\RFID_APP_UP\RfidUpload\
#是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true
# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true
# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL: /api/
# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql

# 附件上传路径
file:
  upload-path: D:\upload
  qrCodeUrl: office.dincher.cn

aliSms:
  path: http://192.168.0.57:8081:8081/aliSms/meetingMgn #会议地址
  smspath: http://192.168.0.57:8081/aliSms/smsMethod #短信验证码
  pathUrl: "pages/SignIn/qiandao/index"

#sa-token和redis配置
sa-token:
  alone-redis:
    database: 1
    # Redis服务器地址
    host: 192.168.0.55
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: rjgs@2016
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

