####设置端口
server:
  port: 7076
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
spring:
  application:
    name: web
  profiles:
    active: local
#jsdc:
#  filepath: D:/newLogisnis/app/webapps/ROOT/
#oa:
#  ip: 58.218.188.178
#  port: 8888